#!/usr/bin/env python3
"""Verify every commit in a range carries a Developer Certificate of Origin sign-off.

Implements the DCO 1.1 check without a third-party action: a supply-chain
dependency is a poor trade for a regex over commit trailers.

Merge commits are skipped. They are generated by the forge rather than authored
by a contributor, so there is no author to assert anything.
"""

from __future__ import annotations

import re
import subprocess
import sys

SIGNOFF_RE = re.compile(r"^Signed-off-by:\s*(?P<name>.+?)\s*<(?P<email>[^>]+)>\s*$", re.MULTILINE)
RECORD_SEP = "\x1e"
FIELD_SEP = "\x1f"


def commits_in_range(base: str, head: str) -> list[dict[str, str]]:
    """Return non-merge commits reachable from head but not base."""
    fmt = FIELD_SEP.join(["%H", "%an", "%ae", "%s", "%B"]) + RECORD_SEP
    proc = subprocess.run(
        ["git", "log", "--no-merges", f"--format={fmt}", f"{base}..{head}"],
        check=True,
        capture_output=True,
        text=True,
    )
    commits = []
    for record in proc.stdout.split(RECORD_SEP):
        record = record.strip("\n")
        if not record:
            continue
        sha, author_name, author_email, subject, body = record.split(FIELD_SEP, 4)
        commits.append(
            {
                "sha": sha,
                "author_name": author_name,
                "author_email": author_email,
                "subject": subject,
                "body": body,
            }
        )
    return commits


def check_commit(commit: dict[str, str]) -> str | None:
    """Return an error string if the commit lacks a matching sign-off."""
    signoffs = SIGNOFF_RE.findall(commit["body"])
    if not signoffs:
        return "no Signed-off-by trailer"

    author = commit["author_email"].strip().lower()
    emails = [email.strip().lower() for _name, email in signoffs]
    if author not in emails:
        found = ", ".join(emails)
        return f"sign-off email does not match author {commit['author_email']} (found: {found})"
    return None


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("usage: check_dco.py <base-sha> <head-sha>", file=sys.stderr)
        return 2

    base, head = argv[1], argv[2]
    try:
        commits = commits_in_range(base, head)
    except subprocess.CalledProcessError as exc:
        print(f"could not enumerate commits {base}..{head}: {exc.stderr.strip()}", file=sys.stderr)
        return 2

    if not commits:
        print("No non-merge commits to check.")
        return 0

    failures = []
    for commit in commits:
        problem = check_commit(commit)
        status = "ok  " if problem is None else "FAIL"
        print(f"  {status} {commit['sha'][:8]} {commit['subject'][:64]}")
        if problem is not None:
            failures.append((commit, problem))

    if failures:
        print(f"\nDCO check failed for {len(failures)} of {len(commits)} commit(s):")
        for commit, problem in failures:
            print(f"  {commit['sha'][:8]}: {problem}")
        print(
            "\nEvery commit must assert the Developer Certificate of Origin 1.1\n"
            "(https://developercertificate.org/) with a sign-off trailer:\n"
            "\n"
            "    Signed-off-by: Your Name <your.email@example.com>\n"
            "\n"
            "Add it automatically with 'git commit -s'. To fix existing commits,\n"
            "amend the most recent with 'git commit --amend -s', or sign off a\n"
            "whole branch with 'git rebase --signoff origin/main'."
        )
        return 1

    print(f"\nDCO check passed: {len(commits)} commit(s) signed off.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
