#!/usr/bin/env python3
"""Generate JSON Schema files from the keel-api Pydantic reference implementation.

Run from this repository root:

    python tools/export_schemas.py --keel-api ../keel-api

Outputs (overwrites if present):

    schemas/permit-v1.schema.json
    schemas/audit-export-bundle.schema.json
    schemas/audit-export-record.schema.json
    schemas/chain-entry.schema.json

Note: schemas/closure-v2.schema.json is hand-maintained and is NOT generated by
this script. The closure record envelope is built dynamically in
keel-api/app/services/execution_closure.py rather than from a Pydantic model;
the closure schema mirrors that wire format and tracks the spec at
spec/closure-v2.md.

Post-processing applied to generated schemas:
  - permit-like fields: add 64-hex patterns for request/binding/chain
    digests and non-negative minimums for token/cost/count fields where the
    public wire format requires non-negative values.
  - chain-entry: tighten ``record_hash``, ``prev_hash``, ``sequence_number``,
    and ``chain_scope`` to non-nullable; add ``chain_format_version`` to the
    required list. The Pydantic model permits null for in-flight records, but
    the wire format requires concrete values in audit-exported entries.
  - audit-export-bundle: constrain ``schema_version`` to enum [1, 2]; add a
    conditional asserting that ``schema_version == 2`` requires
    ``include_chain_entries == true``.
  - all schemas: sanitize developer-comment descriptions on
    RoutingDecision.reason_metadata.

The keel-api package must be importable (its dependencies installed in the
active environment).
"""

from __future__ import annotations

import argparse
import copy
import json
import sys
from pathlib import Path
from typing import Any


_SANITIZED_REASON_METADATA_DESCRIPTION = (
    "Supplemental routing diagnostics. Issuer-defined; readers MUST treat "
    "unknown fields as opaque."
)

_HEX_64_PATTERN = "^[a-f0-9]{64}$"
_HEX_64_FIELDS = {
    "binding_request_hash",
    "prev_hash",
    "record_hash",
    "request_fingerprint",
}
_NONNEGATIVE_FIELDS = {
    "actual_cost_usd_micros",
    "actual_input_tokens",
    "actual_output_tokens",
    "actual_total_tokens",
    "completion_tokens",
    "cost_usd",
    "cost_usd_micros",
    "estimated_cost_usd_micros",
    "estimated_input_tokens",
    "estimated_output_tokens",
    "max_output_tokens_requested",
    "prompt_tokens",
    "record_count",
    "total_tokens",
}
_MINIMUM_BY_FIELD = {
    "sequence_number": 1,
}


def _emit(path: Path, schema: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(Path.cwd())}")


def _walk_sanitize(node: Any) -> None:
    """Recursively sanitize developer-comment descriptions in a JSON Schema."""
    if isinstance(node, dict):
        for key, value in node.items():
            if (
                key == "reason_metadata"
                and isinstance(value, dict)
                and "redact" in str(value.get("description", "")).lower()
            ):
                value["description"] = _SANITIZED_REASON_METADATA_DESCRIPTION
            _walk_sanitize(value)
    elif isinstance(node, list):
        for item in node:
            _walk_sanitize(item)


def _apply_to_schema_branches(prop: dict, field_name: str) -> None:
    """Apply wire-format constraints to a property schema and any anyOf branches."""
    branches = prop.get("anyOf") if isinstance(prop.get("anyOf"), list) else [prop]
    for branch in branches:
        if not isinstance(branch, dict):
            continue
        branch_type = branch.get("type")
        if field_name in _HEX_64_FIELDS and branch_type == "string":
            branch["pattern"] = _HEX_64_PATTERN
        if field_name in _NONNEGATIVE_FIELDS and branch_type in {"integer", "number"}:
            branch["minimum"] = 0
        if field_name in _MINIMUM_BY_FIELD and branch_type in {"integer", "number"}:
            branch["minimum"] = _MINIMUM_BY_FIELD[field_name]


def _tighten_common_wire_fields(schema: dict) -> dict:
    """Apply shared public wire-format constraints to generated schemas."""
    schema = copy.deepcopy(schema)

    def visit(node: Any) -> None:
        if isinstance(node, dict):
            props = node.get("properties")
            if isinstance(props, dict):
                for field_name, prop in props.items():
                    if isinstance(prop, dict):
                        _apply_to_schema_branches(prop, field_name)
            for value in node.values():
                visit(value)
        elif isinstance(node, list):
            for item in node:
                visit(item)

    visit(schema)
    return schema


def _tighten_chain_entry(schema: dict) -> dict:
    """Apply chain-entry tightenings: drop null types and require chain_format_version."""
    schema = copy.deepcopy(schema)
    props = schema.get("properties", {})

    # Drop the null branch from anyOf for fields that are required-non-null in
    # audit-export form per spec/chain-entry.md.
    for field in ("record_hash", "prev_hash", "sequence_number", "chain_scope"):
        prop = props.get(field)
        if isinstance(prop, dict) and "anyOf" in prop:
            non_null = [
                branch
                for branch in prop["anyOf"]
                if not (isinstance(branch, dict) and branch.get("type") == "null")
            ]
            if len(non_null) == 1:
                prop.pop("anyOf")
                prop.update(non_null[0])

    # Pydantic does not include fields with defaults in `required`, but the
    # wire format requires chain_format_version to be present.
    required = list(schema.get("required", []))
    if "chain_format_version" not in required:
        required.append("chain_format_version")
        schema["required"] = required

    return schema


def _tighten_bundle(schema: dict) -> dict:
    """Apply audit-export-bundle tightenings: schema_version enum + conditional."""
    schema = copy.deepcopy(schema)
    props = schema.get("properties", {})

    sv = props.get("schema_version")
    if isinstance(sv, dict):
        sv.pop("type", None)
        sv["enum"] = [1, 2]

    # Add a conditional: schema_version==2 ⇒ include_chain_entries==true and
    # every record carries chain_entries.
    all_of = list(schema.get("allOf", []))
    all_of.append(
        {
            "if": {"properties": {"schema_version": {"const": 2}}, "required": ["schema_version"]},
            "then": {
                "required": ["include_chain_entries"],
                "properties": {
                    "include_chain_entries": {"const": True},
                    "records": {
                        "type": "array",
                        "items": {"required": ["chain_entries"]},
                    },
                },
            },
            "else": {
                "not": {
                    "anyOf": [
                        {"properties": {"include_chain_entries": {"const": True}}, "required": ["include_chain_entries"]},
                    ]
                }
            },
        }
    )
    schema["allOf"] = all_of

    return schema


def _post_process(name: str, schema: dict) -> dict:
    """Apply per-schema tightenings + universal sanitization."""
    if name == "chain-entry":
        schema = _tighten_chain_entry(schema)
    elif name == "audit-export-bundle":
        schema = _tighten_bundle(schema)

    schema = _tighten_common_wire_fields(schema)
    _walk_sanitize(schema)
    return schema


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--keel-api",
        type=Path,
        required=True,
        help="Path to a checked-out keel-api repository.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("schemas"),
        help="Output directory (default: schemas/).",
    )
    args = parser.parse_args()

    keel_api = args.keel_api.resolve()
    if not (keel_api / "app" / "schemas" / "permits.py").is_file():
        print(
            f"ERROR: {keel_api} does not look like a keel-api checkout "
            "(app/schemas/permits.py not found).",
            file=sys.stderr,
        )
        return 2

    sys.path.insert(0, str(keel_api))

    try:
        from app.schemas.permits import (  # type: ignore
            AuditExportBundle,
            AuditExportPermitSource,
            AuditExportRecord,
            ChainEntry,
        )
    except ImportError as exc:
        print(f"ERROR: failed to import keel-api models: {exc}", file=sys.stderr)
        print("Hint: install keel-api dependencies in this environment.", file=sys.stderr)
        return 2

    out_dir = args.out.resolve()
    targets = [
        ("permit-v1", AuditExportPermitSource),
        ("audit-export-record", AuditExportRecord),
        ("audit-export-bundle", AuditExportBundle),
        ("chain-entry", ChainEntry),
    ]
    for name, model in targets:
        raw = model.model_json_schema()
        processed = _post_process(name, raw)
        _emit(out_dir / f"{name}.schema.json", processed)

    print()
    print("note: schemas/closure-v2.schema.json is hand-maintained; not regenerated.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
