#!/usr/bin/env python3
"""Generate JSON Schema files from the keel-api Pydantic reference implementation.

Run from this repository root:

    python tools/export_schemas.py --keel-api ../keel-api

Outputs (overwrites if present):

    schemas/permit-v1.schema.json
    schemas/audit-export-bundle.schema.json
    schemas/audit-export-record.schema.json
    schemas/chain-entry.schema.json

Note: schemas/closure-v2.schema.json and
schemas/audit-export-manifest.schema.json are hand-maintained and are NOT
generated by this script. The closure record and manifest envelopes are built
dynamically in keel-api rather than from Pydantic models; the hand-maintained
schemas mirror those wire formats and track their corresponding spec documents.

Post-processing applied to generated schemas:
  - permit-like fields: add 64-hex patterns for request/binding/chain
    digests and non-negative minimums for token/cost/count fields where the
    public wire format requires non-negative values.
  - chain-entry: tighten ``record_hash``, ``prev_hash``, ``sequence_number``,
    and ``chain_scope`` to non-nullable; add ``chain_format_version`` to the
    required list. The Pydantic model permits null for in-flight records, but
    the wire format requires concrete values in audit-exported entries.
  - audit-export-bundle: constrain ``schema_version`` to enum [1, 2]; add a
    conditional asserting that ``schema_version == 2`` requires
    ``include_chain_entries == true``.
  - all schemas: sanitize developer-comment descriptions on
    RoutingDecision.reason_metadata.

The keel-api package must be importable (its dependencies installed in the
active environment).
"""

from __future__ import annotations

import argparse
import copy
import json
import sys
from pathlib import Path
from typing import Any


_SANITIZED_REASON_METADATA_DESCRIPTION = (
    "Supplemental routing diagnostics. Issuer-defined; readers MUST treat "
    "unknown fields as opaque."
)

_HEX_64_PATTERN = "^[a-f0-9]{64}$"
_HEX_64_FIELDS = {
    "binding_request_hash",
    "prev_hash",
    "record_hash",
    "request_fingerprint",
}
_NONNEGATIVE_FIELDS = {
    "actual_cost_usd_micros",
    "actual_input_tokens",
    "actual_output_tokens",
    "actual_total_tokens",
    "completion_tokens",
    "cost_usd",
    "cost_usd_micros",
    "estimated_cost_usd_micros",
    "estimated_input_tokens",
    "estimated_output_tokens",
    "max_output_tokens_requested",
    "prompt_tokens",
    "record_count",
    "total_tokens",
}
_MINIMUM_BY_FIELD = {
    "sequence_number": 1,
}
_WORKFLOW_ID_PATTERN = "^[A-Za-z0-9_-]{1,255}$"

_PERMIT_EXTENSION_FIELDS = {
    "custom_metadata": {
        "type": ["object", "null"],
        "description": (
            "Optional issuer-defined extension carrier. Reserved keys: shadow_override "
            "(introduced in v1.5.0 for audit annotation of shadow-overridden dispatches). "
            "Conforming validators MUST accept arbitrary additional keys here without rejection."
        ),
        "default": None,
        "additionalProperties": True,
    },
}

_PERMIT_CHAIN_FIELDS = {
    "actor_ref": {
        "anyOf": [
            {
                "additionalProperties": False,
                "properties": {
                    "issuer": {"minLength": 1, "type": "string"},
                    "subject": {"minLength": 1, "type": "string"},
                    "display_label": {
                        "anyOf": [{"type": "string"}, {"type": "null"}],
                        "default": None,
                    },
                },
                "required": ["issuer", "subject"],
                "type": "object",
            },
            {"type": "null"},
        ],
        "default": None,
        "title": "Actor Ref",
    },
    "authority_envelope": {
        "anyOf": [
            {
                "additionalProperties": False,
                "properties": {
                    "actions": {"items": {"type": "string"}, "type": "array", "uniqueItems": True},
                    "tools": {"items": {"type": "string"}, "type": "array", "uniqueItems": True},
                    "providers": {"items": {"type": "string"}, "type": "array", "uniqueItems": True},
                    "models": {"items": {"type": "string"}, "type": "array", "uniqueItems": True},
                    "data_classes": {"items": {"type": "string"}, "type": "array", "uniqueItems": True},
                    "regions": {"items": {"type": "string"}, "type": "array", "uniqueItems": True},
                    "expires_at": {"format": "date-time", "type": "string"},
                },
                "required": [
                    "actions",
                    "tools",
                    "providers",
                    "models",
                    "data_classes",
                    "regions",
                    "expires_at",
                ],
                "type": "object",
            },
            {"type": "null"},
        ],
        "default": None,
        "title": "Authority Envelope",
    },
    "authority_envelope_version": {
        "anyOf": [{"minLength": 1, "type": "string"}, {"type": "null"}],
        "default": None,
        "title": "Authority Envelope Version",
    },
    "policy_version_or_hash": {
        "anyOf": [{"minLength": 1, "type": "string"}, {"type": "null"}],
        "default": None,
        "title": "Policy Version Or Hash",
    },
    "task_description": {
        "anyOf": [{"type": "string"}, {"type": "null"}],
        "default": None,
        "title": "Task Description",
    },
    "usage_limits": {
        "anyOf": [{"type": "object"}, {"type": "null"}],
        "default": None,
        "title": "Usage Limits",
    },
}


def _emit(path: Path, schema: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    try:
        display_path = path.relative_to(Path.cwd())
    except ValueError:
        display_path = path
    print(f"wrote {display_path}")


def _walk_sanitize(node: Any) -> None:
    """Recursively sanitize developer-comment descriptions in a JSON Schema."""
    if isinstance(node, dict):
        for key, value in node.items():
            if (
                key == "reason_metadata"
                and isinstance(value, dict)
                and "redact" in str(value.get("description", "")).lower()
            ):
                value["description"] = _SANITIZED_REASON_METADATA_DESCRIPTION
            _walk_sanitize(value)
    elif isinstance(node, list):
        for item in node:
            _walk_sanitize(item)


def _apply_to_schema_branches(prop: dict, field_name: str) -> None:
    """Apply wire-format constraints to a property schema and any anyOf branches."""
    branches = prop.get("anyOf") if isinstance(prop.get("anyOf"), list) else [prop]
    for branch in branches:
        if not isinstance(branch, dict):
            continue
        branch_type = branch.get("type")
        if field_name in _HEX_64_FIELDS and branch_type == "string":
            branch["pattern"] = _HEX_64_PATTERN
        if field_name in _NONNEGATIVE_FIELDS and branch_type in {"integer", "number"}:
            branch["minimum"] = 0
        if field_name in _MINIMUM_BY_FIELD and branch_type in {"integer", "number"}:
            branch["minimum"] = _MINIMUM_BY_FIELD[field_name]
        if field_name == "workflow_id" and branch_type == "string":
            branch["minLength"] = 1
            branch["maxLength"] = 255
            branch["pattern"] = _WORKFLOW_ID_PATTERN


def _tighten_common_wire_fields(schema: dict) -> dict:
    """Apply shared public wire-format constraints to generated schemas."""
    schema = copy.deepcopy(schema)

    def visit(node: Any) -> None:
        if isinstance(node, dict):
            props = node.get("properties")
            if isinstance(props, dict):
                for field_name, prop in props.items():
                    if isinstance(prop, dict):
                        _apply_to_schema_branches(prop, field_name)
            for value in node.values():
                visit(value)
        elif isinstance(node, list):
            for item in node:
                visit(item)

    visit(schema)
    return schema


def _tighten_chain_entry(schema: dict) -> dict:
    """Apply chain-entry tightenings: drop null types and require chain_format_version."""
    schema = copy.deepcopy(schema)
    props = schema.get("properties", {})

    # Drop the null branch from anyOf for fields that are required-non-null in
    # audit-export form per spec/chain-entry.md.
    for field in ("record_hash", "prev_hash", "sequence_number", "chain_scope"):
        prop = props.get(field)
        if isinstance(prop, dict) and "anyOf" in prop:
            non_null = [
                branch
                for branch in prop["anyOf"]
                if not (isinstance(branch, dict) and branch.get("type") == "null")
            ]
            if len(non_null) == 1:
                prop.pop("anyOf")
                prop.update(non_null[0])

    # Pydantic does not include fields with defaults in `required`, but the
    # wire format requires chain_format_version to be present.
    required = list(schema.get("required", []))
    if "chain_format_version" not in required:
        required.append("chain_format_version")
        schema["required"] = required

    return schema


def _strip_internal_chain_entry_fields(schema: dict) -> dict:
    """Remove reference-model convenience fields outside chain-entry v1."""
    schema = copy.deepcopy(schema)

    def is_chain_entry_properties(props: dict) -> bool:
        return {
            "chain_format_version",
            "chain_scope",
            "created_at",
            "event_id",
            "event_type",
            "payload_json",
            "prev_hash",
            "record_hash",
            "sequence_number",
        }.issubset(props)

    def visit(node: Any) -> None:
        if isinstance(node, dict):
            props = node.get("properties")
            if isinstance(props, dict) and is_chain_entry_properties(props):
                props.pop("permit_id", None)
                props.pop("request_id", None)
            for value in node.values():
                visit(value)
        elif isinstance(node, list):
            for item in node:
                visit(item)

    visit(schema)
    return schema


def _tighten_bundle(schema: dict) -> dict:
    """Apply audit-export-bundle tightenings: schema_version enum + conditional."""
    schema = copy.deepcopy(schema)
    props = schema.get("properties", {})

    sv = props.get("schema_version")
    if isinstance(sv, dict):
        sv.pop("type", None)
        sv["enum"] = [1, 2]

    # Add a conditional: schema_version==2 ⇒ include_chain_entries==true and
    # every record carries chain_entries.
    all_of = list(schema.get("allOf", []))
    all_of.append(
        {
            "if": {"properties": {"schema_version": {"const": 2}}, "required": ["schema_version"]},
            "then": {
                "required": ["include_chain_entries"],
                "properties": {
                    "include_chain_entries": {"const": True},
                    "records": {
                        "type": "array",
                        "items": {"required": ["chain_entries"]},
                    },
                },
            },
            "else": {
                "not": {
                    "anyOf": [
                        {"properties": {"include_chain_entries": {"const": True}}, "required": ["include_chain_entries"]},
                    ]
                }
            },
        }
    )
    schema["allOf"] = all_of

    return schema


def _add_permit_chain_fields(schema: dict) -> dict:
    """Allow optional Permit Chain v1 fields and extension fields in closed Permit schemas."""
    schema = copy.deepcopy(schema)

    def is_permit_properties(props: dict) -> bool:
        return {
            "id",
            "project_id",
            "parent_permit_id",
            "delegation_depth",
            "request_fingerprint",
            "policy_version",
        }.issubset(props)

    def visit(node: Any) -> None:
        if isinstance(node, dict):
            props = node.get("properties")
            if isinstance(props, dict) and is_permit_properties(props):
                for field_name, field_schema in _PERMIT_CHAIN_FIELDS.items():
                    props.setdefault(field_name, copy.deepcopy(field_schema))
                for field_name, field_schema in _PERMIT_EXTENSION_FIELDS.items():
                    props.setdefault(field_name, copy.deepcopy(field_schema))
            for value in node.values():
                visit(value)
        elif isinstance(node, list):
            for item in node:
                visit(item)

    visit(schema)
    return schema


def _post_process(name: str, schema: dict) -> dict:
    """Apply per-schema tightenings + universal sanitization."""
    if name == "chain-entry":
        schema = _tighten_chain_entry(schema)
    elif name == "audit-export-bundle":
        schema = _tighten_bundle(schema)

    schema = _tighten_common_wire_fields(schema)
    schema = _strip_internal_chain_entry_fields(schema)
    if name in {"permit-v1", "audit-export-record", "audit-export-bundle"}:
        schema = _add_permit_chain_fields(schema)
    _walk_sanitize(schema)
    return schema


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--keel-api",
        type=Path,
        required=True,
        help="Path to a checked-out keel-api repository.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("schemas"),
        help="Output directory (default: schemas/).",
    )
    args = parser.parse_args()

    keel_api = args.keel_api.resolve()
    if not (keel_api / "app" / "schemas" / "permits.py").is_file():
        print(
            f"ERROR: {keel_api} does not look like a keel-api checkout "
            "(app/schemas/permits.py not found).",
            file=sys.stderr,
        )
        return 2

    sys.path.insert(0, str(keel_api))

    try:
        from app.schemas.permits import (  # type: ignore
            AuditExportBundle,
            AuditExportPermitSource,
            AuditExportRecord,
            ChainEntry,
        )
    except ImportError as exc:
        print(f"ERROR: failed to import keel-api models: {exc}", file=sys.stderr)
        print("Hint: install keel-api dependencies in this environment.", file=sys.stderr)
        return 2

    out_dir = args.out.resolve()
    targets = [
        ("permit-v1", AuditExportPermitSource),
        ("audit-export-record", AuditExportRecord),
        ("audit-export-bundle", AuditExportBundle),
        ("chain-entry", ChainEntry),
    ]
    for name, model in targets:
        raw = model.model_json_schema()
        processed = _post_process(name, raw)
        _emit(out_dir / f"{name}.schema.json", processed)

    print()
    print("note: closure-v2 and audit-export-manifest schemas are hand-maintained; not regenerated.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
